FROM castation-buildenv
RUN apt-get update && apt-get install -y --no-install-recommends rsync pkg-config python3-venv bison flex glslang-tools llvm-18-dev libclang-18-dev libclc-18-dev libclc-18 libllvmspirvlib-18-dev llvm-spirv-18 && rm -rf /var/lib/apt/lists/*
RUN python3 -m venv /opt/radv-tools && /opt/radv-tools/bin/pip install --no-cache-dir meson==1.9.2 mako==1.3.10 packaging==25.0 PyYAML==6.0.2
ENV PATH=/opt/radv-tools/bin:$PATH
ENV CC=clang-18 CXX=clang++-18 BUILD_JOBS=4
