if(CMAKE_CROSSCOMPILING)
  set(CODEC_BUILD "${CMAKE_CURRENT_SOURCE_DIR}/build/ffmpeg-ps5")
else()
  set(CODEC_BUILD "${CMAKE_CURRENT_SOURCE_DIR}/build/ffmpeg-host")
endif()
foreach(name IN ITEMS avcodec avutil)
  if(NOT EXISTS "${CODEC_BUILD}/lib${name}/lib${name}.a")
    message(FATAL_ERROR "Build pinned XMA codecs with tools/build-audio-codecs.sh first")
  endif()
  add_library(xenia_${name} STATIC IMPORTED)
  set_target_properties(xenia_${name} PROPERTIES IMPORTED_LOCATION "${CODEC_BUILD}/lib${name}/lib${name}.a")
endforeach()
file(GLOB AUDIO_SOURCES CONFIGURE_DEPENDS "${XENIA_SOURCE}/src/xenia/apu/*.cc")
list(FILTER AUDIO_SOURCES EXCLUDE REGEX "/(xma_context|xma_decoder)\\.cc$")
list(APPEND AUDIO_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/build/generated-sources/xma_context.cc"
  "${CMAKE_CURRENT_SOURCE_DIR}/build/generated-sources/xma_decoder.cc")
add_library(xenia_audio_engine STATIC ${AUDIO_SOURCES})
target_sources(xenia_audio_engine PRIVATE platform/ps5/native_audio.cpp)
target_include_directories(xenia_audio_engine PUBLIC include)
target_link_libraries(xenia_audio_engine PUBLIC xenia_guest_kernel xenia_avcodec xenia_avutil)
target_include_directories(xenia_audio_engine PRIVATE "${CODEC_BUILD}" "${XENIA_SOURCE}/third_party/FFmpeg")
target_compile_definitions(xenia_audio_engine PRIVATE NDEBUG)
target_compile_options(xenia_audio_engine PRIVATE -ffunction-sections -fdata-sections -fno-char8_t -mavx)
add_executable(xenia-audio-codec-contract src/audio_codec_contract.cpp)
target_include_directories(xenia-audio-codec-contract PRIVATE "${CODEC_BUILD}" "${XENIA_SOURCE}/third_party/FFmpeg")
target_link_libraries(xenia-audio-codec-contract PRIVATE xenia_audio_engine)
target_link_options(xenia-audio-codec-contract PRIVATE -Wl,--gc-sections)
if(NOT CMAKE_CROSSCOMPILING)
  target_link_libraries(xenia-audio-codec-contract PRIVATE pthread m)
  add_test(NAME actual_xma_codec_registration COMMAND xenia-audio-codec-contract)
endif()
