# A platform boundary, not a replacement for Xenia's Xenos renderer.
set(VULKAN_HEADERS "${XENIA_SOURCE}/third_party/Vulkan-Headers/include")
if(NOT EXISTS "${VULKAN_HEADERS}/vulkan/vulkan.h")
  message(FATAL_ERROR "Initialize the pinned Xenia Vulkan-Headers submodule")
endif()
add_library(xbox360ps5_vulkan_platform STATIC platform/ps5/vulkan_platform.cpp)
target_include_directories(xbox360ps5_vulkan_platform PUBLIC include "${VULKAN_HEADERS}")
target_compile_options(xbox360ps5_vulkan_platform PRIVATE -Wall -Wextra -Wno-missing-field-initializers)
add_executable(vulkan-platform-contract src/vulkan_platform_contract.cpp)
target_link_libraries(vulkan-platform-contract PRIVATE xbox360ps5_vulkan_platform)
if(NOT CMAKE_CROSSCOMPILING)
  add_test(NAME vulkan_platform_contract COMMAND vulkan-platform-contract)
  add_executable(vulkan-transfer-probe src/vulkan_transfer_probe.cpp)
  target_link_libraries(vulkan-transfer-probe PRIVATE xbox360ps5_vulkan_platform dl)
endif()
